version: "3.5"
services:
  cardano-node:
    image: inputoutput/cardano-node:1.30.1
    container_name: cardano_node
    environment:
      NETWORK: 
    volumes:
      - ./cardano-node/db/${NETWORK}:/data
      - /tmp/ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  cardano-wallet:
    image: inputoutput/cardano-wallet:2021.9.29
    volumes:
      - ./cardano-wallet/db/${NETWORK}:/wallet-db
      - /tmp/ipc:/ipc
    ports:
      - 8090:8090
    entrypoint: []
    command: bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ($$CMD --testnet /config/${NETWORK}/genesis-byron.json)
      "
    environment:
      CMD: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK: 
    restart: on-failure
    container_name: cardano_wallet
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
